# Shell variables
# Generated by 'wal'
wallpaper='/home/rohnch/.config/luna_theme/WALL.jpg'

# Special
background='#0F130E'
foreground='#d4dfe8'
cursor='#d4dfe8'

# Colors
color0='#0F130E'
color1='#3068c1'
color2='#3f90cf'
color3='#5e74d6'
color4='#e6ba9c'
color5='#8bbae2'
color6='#a3c8e8'
color7='#d4dfe8'
color8='#949ca2'
color9='#3068c1'
color10='#3f90cf'
color11='#5e74d6'
color12='#e6ba9c'
color13='#8bbae2'
color14='#a3c8e8'
color15='#d4dfe8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
