# Shell variables
# Generated by 'wal'
wallpaper='/home/rohnch/.config/luna_theme/WALL.jpg'

# Special
background='#151010'
foreground='#c3c3c5'
cursor='#c3c3c5'

# Colors
color0='#151010'
color1='#d06446'
color2='#d28c4d'
color3='#d99a68'
color4='#366ecc'
color5='#ce3c82'
color6='#477ed1'
color7='#c3c3c5'
color8='#888889'
color9='#d06446'
color10='#d28c4d'
color11='#d99a68'
color12='#366ecc'
color13='#ce3c82'
color14='#477ed1'
color15='#c3c3c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
