# Shell variables
# Generated by 'wal'
wallpaper='/home/rohnch/.config/luna_theme/WALL.jpg'

# Special
background='#101210'
foreground='#c6d0db'
cursor='#c6d0db'

# Colors
color0='#101210'
color1='#80b62d'
color2='#ca9232'
color3='#2a68aa'
color4='#4b8dd2'
color5='#529bd3'
color6='#6a99da'
color7='#c6d0db'
color8='#8a9199'
color9='#80b62d'
color10='#ca9232'
color11='#2a68aa'
color12='#4b8dd2'
color13='#529bd3'
color14='#6a99da'
color15='#c6d0db'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
