#!/bin/sh
# shellcheck disable=SC2139
alias ls="ls --group-directories-first --color=auto -v"
alias grep="grep --color"
alias ll="ls -vlh"
alias l="ls -1hv"
alias Gn="poweroff"
alias z="zathura --fork"
alias d="sudo dnf"
alias gp='gnuplot'
alias s='sudo'
alias v='$EDITOR'
alias sv='sudoedit'
alias py='python3 -q'
alias pyy='py -i $XDG_CONFIG_HOME/python/mypyenv.py'
alias nb='newsboat'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias o='xdg-open'
alias octave="octave -f"
alias oc="/usr/bin/octave -q"
alias smi='sudo make install'
alias t='todo.sh'
alias ip='ip -c=auto'
alias config='git --git-dir=$HOME/.cfg --work-tree=$HOME'
alias mpv-nvdec='mpv --gpu-context=waylandvk --hwdec=nvdec'
alias del="trash-put"
alias ssh-insecure="OPENSSL_CONF=~/.ssh/insecure-openssl.cnf ssh"


# youtube-dl
alias ytdlv="yt-dlp --cookies-from-browser $BROWSER -N 10 --add-metadata -f 'bestvideo[height<=$LUNA_YPLAY_RES]+bestaudio' -o '%(title)s.%(ext)s'"
alias ytdla="yt-dlp --cookies-from-browser $BROWSER -N 10 --audio-format best --extract-audio --add-metadata -o '%(title)s.%(ext)s'"
alias ytdlm="yt-dlp --cookies-from-browser $BROWSER -N 10 --format=bestaudio --extract-audio --add-metadata --output='$LUNA_MUSIC_DIR/%(title)s.%(ext)s'"
alias mpv-yta="mpv --audio-display=external-first"

sendit() {
        file_to_send="-"
        [ -n "$1" ] && file_to_send="$1"
        curl --progress-bar -F "file=@$file_to_send" https://0x0.st
}



rm() {
        printf "[$(pwd)] run: \"rm ${*}\", Are you sure? (y/n)";
        read -k ans; echo ""
        [ "$ans" = 'y' ] && "/bin/rm" ${*}
}

function ] {
        ans="$(py -c "from math import *; print($*)")"
        ans="${ans#ans = }"
        echo "$ans"; export ans
}

function \? {
        curl --silent dict://dict.org/lookup:"$*" | less
}

alias ]='noglob ]'
alias \?="noglob \?"
